#!/usr/bin/env bash
#write a Bash script that configures a new Ubuntu machine to respect above requirements
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start
