#!/usr/bin/env bash
#Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

n=0

while [ $n -le 10 ]
do
	if [ $n -ne 9 ]
	then
		echo "Best School"
	else
		echo "Hi"
	fi
	((n+=1))
done
